name: generate selected *.md files

on:
  push:
    branches: [ main ]
#    paths:
#      - '.github/workflows/gen_md_files.yml'
#      - '.github/scripts/gen_readme.md.sh'
#  schedule:
#    - cron: '20 12 * * *'
  workflow_dispatch:

env:
  SCRIPT01: .github/scripts/gen_readme.md.sh

jobs:
  generate-and-deploy:
    runs-on: ubuntu-latest
#    if: github.repository == ''
    steps:

      - name: clone
        uses: actions/checkout@main
        with:
          clean: false

      - name: generate
        env:
          LANG: en_US.utf8
        run: |
          echo run ${{ env.SCRIPT01 }} && $SHELL ./${{ env.SCRIPT01 }}

      - name: commit
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global --add safe.directory $GITHUB_WORKSPACE
          git pull
          git add .
          git status
          git config --local user.name github-actions[bot]
          git config --local user.email github-actions[bot]@users.noreply.github.com
          git diff --cached --quiet && exit 0 || git commit -m "docs: Update MD Files"
          git config --local credential.helper '!x() { echo "password=$GITHUB_TOKEN"; };x'
          git push origin $GITHUB_REF_NAME
